snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://%redis_host%
            logging: '%kernel.debug%'
        cache:
            type: phpredis
            alias: cache
            dsn: redis://%redis_host%/1
            logging: true
        session:
            type: phpredis
            alias: session
            dsn: redis://%redis_host%/2
        monolog:
            type: phpredis
            alias: monolog
            dsn: redis://%redis_host%/3
            logging: false
    session:
        client: session
        ttl: 7200
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: cache
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
    swiftmailer:
        client: default
        key: swiftmailer
    monolog:
        client: monolog
        key: monolog