services:
#    elastic.example:
#        class: ElasticBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    elastic.manager.curl:
        class: PeerboardBundle\Service\CURLManager
